config/routes.rb
Rails.application.routes.draw do
  root to: 'topics#index'

  get 'topics', to: 'topics#index'
  get 'topics/:id', to: 'topics#show', as: 'topic'

  post 'topics', to: 'topics#create'
end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :is_thread, type: Boolean
  has_many :replies, class_name: Topic, inverse_of: :parent
  belongs_to :parent, class_name: Topic, inverse_of: :replies, optional: true

  def self.find_all_threads
    return where(is_thread: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.find_all_threads
    @new_topic = Topic.new
  end

  def show
    @topic = Topic.find(params[:id])
    @new_topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.is_thread = topic_params[:parent_id].empty?
    begin
      @topic.save!
      if topic_params[:parent_id].empty?
        redirect_to topics_path
      else
        @topic = Topic.find(params[:topic][:redirect_id])
        redirect_to @topic
      end
    rescue => e
      puts "Error: #{e}"
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForunTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to root_path do %>
      [home]
    <% end %>
    <%= yield %>
  </body>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/partials/_comments.html.erb
<ol>
  <% children.each do |child| %>
    <li>
      <%= child.created_at %> <%= child.title %>
      <button type="button" name="reply" class="reply-btn" data-topic-id="<%= child.id %>">reply</button>
      <div class="hidden form-wrapper">
          <%= render partial: 'partials/new_topic_form', locals: { parent_id: child.id, redirect_id: redirect_id } %>
      </div>
      <%= render partial: 'partials/comments', locals: { children: child.replies, redirect_id: redirect_id  } %>
    </li>
  <% end %>
</ol>

app/views/partials/_new_topic_form.html.erb
<%= form_for @new_topic, url: { action: "create" } do |f| %>
  <%= f.hidden_field :parent_id, value: parent_id %>
  <%= f.hidden_field :redirect_id, value: redirect_id %>
  <%= f.text_area :title, size: "60x12" %>
  <%= f.submit "Submit query" %>
<% end %>

app/views/topics/index.html.erb
<%= render partial: 'partials/new_topic_form', locals: { parent_id: nil, redirect_id: nil, not_hidden: true } %>

<ol class="first">
  <% @topics.each do |topic| %>
      <li>
        <%= link_to topic_path(topic) do %>
          <%= topic.created_at %> <%= topic.title %>
        <% end %>
      </li>
  <% end %>
</ol>

app/views/topics/show.html.erb
<ol class="first">
  <li>
    <%= @topic.created_at %> <%= @topic.title %>
    <button type="button" name="reply" class="reply-btn">reply</button>
    <div class="hidden form-wrapper">
      <%= render partial: 'partials/new_topic_form', locals: { parent_id: @topic.id, redirect_id: @topic.id } %>
    </div>
    <%= render partial: "partials/comments", locals: { children: @topic.replies, redirect_id: @topic.id  } %>
  </li>
</ol>